name: DNFr

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Preparation:

    runs-on: [ windows-latest ]
  
    steps:

    - uses: actions/checkout@v2
      name: Clone Repo
      
#    - name: Setup .NET Framework
#     uses: actions/setup-dotnet@v1
#      with:
#       dotnet-version: 3.1.301
#   - name: Install dependencies
#     run: dotnet restore
#    - name: Build
#      run: dotnet build --configuration Release --no-restore
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
  
    - name: setup-NuGet
      uses: NuGet/setup-nuget@v1.0.5

  Build:
    runs-on: [ windows-latest ]  
    needs: [Preparation]  
    steps:      
  
    - name: restore-NuGet pakages
      run : nuget restore CalcSharp.sln
 
    - name: build Solution
      run: msbuild CalcSharp.sln #/p:Configuration-Release
      
  Test:
    runs-on: [ windows-latest ]
    needs: [Build]
    steps:
    
    - name: test solution 
      run: dotnet test --no-restore --verbosity normal
